import Head from 'next/head'
import mesh from "react-three-fiber"
import styles from '@/styles/Home.module.css'
import { Canvas } from 'react-three-fiber'
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <div className='bg-black w-full h-[100vh]'>
      <Canvas>
      <mesh scale={[1,2,1]} position={[1,2,-4]}>
        <sphereGeometry args={[1.5,32,32]}/>
        {/* <torusKnotGeometry /> */}
        <meshNormalMaterial wireframe/>
      </mesh>
      </Canvas>
     </div>
    </>
  )
}
